/**
 * Base utilities for GRASS GIS multi-agent workflow system
 * Provides common functionality for file communication, logging, and agent coordination
 */

import { promises as fs } from 'fs';
import path from 'path';
import { tool } from '@open-code/tools';

export interface AgentContext {
  sessionId: string;
  workflowId: string;
  agentName: string;
  timestamp: string;
}

export interface AgentResult {
  success: boolean;
  data: any;
  errors?: string[];
  performance?: {
    duration: number;
    memoryUsage?: number;
  };
}

export class AgentFramework {
  private context: AgentContext;

  constructor(agentName: string, workflowId?: string) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const sessionId = `grass_agent_${agentName}_${workflowId || 'default'}_${timestamp}`;

    this.context = {
      sessionId,
      workflowId: workflowId || 'default',
      agentName,
      timestamp
    };
  }

  /**
   * Write human-readable markdown report
   */
  async writeMarkdownReport(content: string, step?: string): Promise<void> {
    const filename = `${this.context.agentName}_${this.context.timestamp}${step ? `_${step}` : ''}.md`;
    const filepath = path.join('temp', 'agent_outputs', this.context.workflowId, filename);

    await fs.mkdir(path.dirname(filepath), { recursive: true });
    await fs.writeFile(filepath, content, 'utf-8');

    this.log(`Markdown report written: ${filepath}`);
  }

  /**
   * Write machine-readable JSON data
   */
  async writeJsonData(data: any, step?: string): Promise<void> {
    const filename = `${this.context.agentName}_${this.context.timestamp}${step ? `_${step}` : ''}.json`;
    const filepath = path.join('temp', 'agent_outputs', this.context.workflowId, filename);

    await fs.mkdir(path.dirname(filepath), { recursive: true });
    await fs.writeFile(filepath, JSON.stringify(data, null, 2), 'utf-8');

    this.log(`JSON data written: ${filepath}`);
  }

  /**
   * Read previous agent output
   */
  async readAgentOutput(agentName: string, workflowId?: string): Promise<any> {
    const targetWorkflowId = workflowId || this.context.workflowId;
    const pattern = `${agentName}_*.json`;
    const outputDir = path.join('temp', 'agent_outputs', targetWorkflowId);

    try {
      const files = await fs.readdir(outputDir);
      const jsonFiles = files.filter(f => f.startsWith(agentName) && f.endsWith('.json'));

      if (jsonFiles.length === 0) {
        return null;
      }

      // Get most recent file
      const latestFile = jsonFiles.sort().pop();
      const filepath = path.join(outputDir, latestFile!);
      const content = await fs.readFile(filepath, 'utf-8');

      return JSON.parse(content);
    } catch (error) {
      this.log(`Warning: Could not read agent output for ${agentName}: ${error}`);
      return null;
    }
  }

  /**
   * Log agent activity
   */
  log(message: string, level: 'INFO' | 'WARN' | 'ERROR' = 'INFO'): void {
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] ${level}: ${message}`;

    // Write to console for immediate feedback
    console.log(logEntry);

    // Write to log file
    const logFile = path.join('logs', `${this.context.sessionId}.log`);
    fs.appendFile(logFile, logEntry + '\n').catch(err =>
      console.error('Failed to write to log file:', err)
    );
  }

  /**
   * Track performance metrics
   */
  async trackPerformance<T>(operation: () => Promise<T>): Promise<{ result: T; performance: AgentResult['performance'] }> {
    const startTime = Date.now();
    const startMemory = process.memoryUsage?.().heapUsed || 0;

    try {
      const result = await operation();
      const endTime = Date.now();
      const endMemory = process.memoryUsage?.().heapUsed || 0;

      const performance = {
        duration: endTime - startTime,
        memoryUsage: endMemory - startMemory
      };

      this.log(`Performance: ${performance.duration}ms, memory: ${performance.memoryUsage} bytes`);

      return { result, performance };
    } catch (error) {
      const endTime = Date.now();
      this.log(`Operation failed after ${endTime - startTime}ms: ${error}`, 'ERROR');
      throw error;
    }
  }

  /**
   * Get current context
   */
  getContext(): AgentContext {
    return { ...this.context };
  }

  /**
   * Generate session summary
   */
  async generateSummary(success: boolean, details: any): Promise<string> {
    const summary = `# Agent Session Summary

**Agent**: ${this.context.agentName}
**Session ID**: ${this.context.sessionId}
**Workflow ID**: ${this.context.workflowId}
**Timestamp**: ${this.context.timestamp}
**Status**: ${success ? 'SUCCESS' : 'FAILED'}

## Details
${typeof details === 'string' ? details : JSON.stringify(details, null, 2)}

---
Generated by GRASS Multi-Agent Framework v1.0
`;

    return summary;
  }
}

// Utility function for creating markdown reports
export function createMarkdownReport(title: string, sections: Record<string, string>): string {
  let content = `# ${title}\n\n`;

  for (const [sectionTitle, sectionContent] of Object.entries(sections)) {
    content += `## ${sectionTitle}\n\n${sectionContent}\n\n`;
  }

  content += `---\n*Generated by ${title} Agent*`;

  return content;
}

// Error recovery utility
export async function withErrorRecovery<T>(
  operation: () => Promise<T>,
  context: string,
  maxRetries: number = 2
): Promise<T> {
  let lastError: Error;

  for (let attempt = 1; attempt <= maxRetries + 1; attempt++) {
    try {
      return await operation();
    } catch (error) {
      lastError = error as Error;
      console.log(`Attempt ${attempt} failed for ${context}: ${error}`);

      if (attempt <= maxRetries) {
        // Wait before retry (exponential backoff)
        await new Promise(resolve => setTimeout(resolve, Math.pow(2, attempt) * 1000));
      }
    }
  }

  throw new Error(`Operation failed after ${maxRetries + 1} attempts: ${lastError!.message}`);
}